[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = mdairy

; Server
xmlrpc_port = 8069
longpolling_port = 8072
; Set to True to enable dev mode during development
dev_mode = False

; Workers (set to 0 for single-thread mode in dev)
workers = 0

; File storage
data_dir = /var/lib/odoo

; Log level: debug_rpc, debug, info, warning, error, critical
log_level = info
